local NumberFormat = require("lib.number_format")

describe("NumberFormat", function()
  describe(".suffixed", function()
    it("truncates to a whole number below 1000", function()
      assert.are.equal("999", NumberFormat.suffixed(999))
      assert.are.equal("999", NumberFormat.suffixed(999.99999))
      assert.are.equal("2", NumberFormat.suffixed(2.9))
      assert.are.equal("0", NumberFormat.suffixed(1 / 3))
      assert.are.equal("0", NumberFormat.suffixed(0))
    end)

    it("shows one fixed decimal digit from 1000 up to 10000", function()
      assert.are.equal("1.0k", NumberFormat.suffixed(1000))
      assert.are.equal("2.0k", NumberFormat.suffixed(2000))
      assert.are.equal("9.9k", NumberFormat.suffixed(9940))
      assert.are.equal("4.3k", NumberFormat.suffixed(4399))
    end)

    it("drops the decimal digit from 10000 up to 1000000", function()
      assert.are.equal("10k", NumberFormat.suffixed(10000))
      assert.are.equal("23k", NumberFormat.suffixed(23456))
      assert.are.equal("999k", NumberFormat.suffixed(999400))
    end)

    it("truncates instead of rounding, so a value never displays as more than it is", function()
      assert.are.equal("9.9k", NumberFormat.suffixed(9999))
      assert.are.equal("999k", NumberFormat.suffixed(999999))
      assert.are.equal("1.9M", NumberFormat.suffixed(1999999))
      assert.are.equal("999.9M", NumberFormat.suffixed(999999999))
      assert.are.equal("999.9B", NumberFormat.suffixed(999999999999))
    end)

    it("uses M, B and T with one decimal digit", function()
      assert.are.equal("1.0M", NumberFormat.suffixed(1e6))
      assert.are.equal("1.5M", NumberFormat.suffixed(1.5e6))
      assert.are.equal("123.4M", NumberFormat.suffixed(123456789))
      assert.are.equal("2.0B", NumberFormat.suffixed(2e9))
      assert.are.equal("3.0T", NumberFormat.suffixed(3e12))
    end)

    it("keeps counting in T beyond a thousand T", function()
      assert.are.equal("1000.0T", NumberFormat.suffixed(1e15))
    end)

    it("keeps the sign of a negative value", function()
      assert.are.equal("-2.5k", NumberFormat.suffixed(-2500))
      assert.are.equal("-23k", NumberFormat.suffixed(-23456))
      assert.are.equal("-2", NumberFormat.suffixed(-2.5))
    end)

    it("does not show a negative zero", function()
      assert.are.equal("0", NumberFormat.suffixed(-0.5))
    end)
  end)
end)
